voice_web/voice_app/urls.py
from django.conf.urls import url

from voice_app import views

app_name = 'voice_app'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^relogin$', views.relogin, name='relogin'),
    url(r'^userinfo$', views.user_info, name='userinfo'),
    url(r'^add_blog$', views.add_blog, name='add_blog'),
    url(r'^show_blog$', views.show_blog, name='show_blog'),
    url(r'^blog_list$', views.blog_list, name='blog_list'),
    url(r'^edit_blog$', views.edit_blog, name='edit_blog'),
    url(r'^remove_blog$', views.remove_blog, name='remove_blog'),
    url(r'^add_cat$', views.add_cat, name='add_cat'),
    url(r'^all_cats$', views.all_cats, name='all_cats'),
    url(r'^edit_cat$', views.edit_cat, name='edit_cat'),
    url(r'^remove_cat$', views.remove_cat, name='remove_cat'),
    url(r'^add_comment$', views.add_comment, name='add_comment'),
    url(r'^edit_comment$', views.edit_comment, name='edit_comment'),
    url(r'^remove_comment$', views.remove_comment, name='remove_comment'),
    url(r'^all_comments$', views.all_comments, name='all_comments'),
    url(r'^all_comments$', views.all_comments, name='all_comments'),
    url(r'^show_post$', views.show_post, name='show_post'),
    url(r'^add_post$', views.add_post, name='add_post'),
    url(r'^remove_post$', views.remove_post, name='remove_post'),
    url(r'^edit_post$', views.edit_post, name='edit_post'),
    url(r'^change_nickname$', views.change_nickname, name='change_nickname'),

    url(r'^edit_blog$', views.edit_blog, name='edit_blog'),
    url(r'^edit_blog$', views.edit_blog, name='edit_blog'),
    url(r'^edit_blog$', views.edit_blog, name='edit_blog'),
]

voice_web/voice_web/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('voice_app.urls')),
    path('admin/', admin.site.urls),
]

voice_web/voice_app/models.py
from django.db import models

# Create your models here.

voice_web/voice_app/forms.py
from django import forms


class BaseFrom(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class TaskForm(BaseFrom):
    title = forms.CharField(max_length=100)
    tags = forms.CharField(label='Tags, divided by comma', max_length=500, required=False)
    date = forms.DateField(initial=None, widget=forms.SelectDateWidget, required=False)
    days_interval = forms.IntegerField(max_value=5000, min_value=1, initial=None, required=False)


class ReloginForm(BaseFrom):
    login = forms.CharField(max_length=100)


class AddBlogForm(BaseFrom):
    title = forms.CharField(max_length=300)


class EditBlogForm(BaseFrom):
    title = forms.CharField(max_length=300)


class AddCatForm(BaseFrom):
    name = forms.CharField(max_length=300)


class EditCatForm(BaseFrom):
    name = forms.CharField(max_length=300)


class AddCommentForm(BaseFrom):
    content = forms.CharField(max_length=300)


class EditCommentForm(BaseFrom):
    content = forms.CharField(max_length=300)


class AddPostForm(BaseFrom):
    title = forms.CharField(max_length=300)
    content = forms.CharField(max_length=3000)
    category_id = forms.CharField()


class EditPostForm(BaseFrom):
    title = forms.CharField(max_length=300)
    content = forms.CharField(max_length=3000)
    category_id = forms.CharField()


class ChangeNickForm(BaseFrom):
    nickname = forms.CharField(max_length=100)

voice_web/voice_app/views.py
from django.shortcuts import render
from django.shortcuts import redirect, render
from django.urls import reverse

from voice_app.context import create_ctx
from voice_app.forms import *
from voice_cli.permission_utils import pass_current_user_id_factory
from voice_cli.cli_utils.cli_voice import cli_voice
from voice_cli.presenter_utils import user2str, fake2str
from voice_cli.error_handling import error_handler_wrapper
from voice_cli.config_utils import change_current_user, get_default_config_path, change_current_fake

from voice_cli.permission_utils import (pass_current_user_id)
from voice_cli.cli_utils.cli_voice import cli_voice
from voice_cli.presenter_utils import blog2str
from voice_cli.error_handling import error_handler_wrapper
from voice.models import *


def index(request):
    return render(request, 'voice_app/index.html')


def relogin(request):
    if request.method == 'POST':
        form = ReloginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['login']

            config_path = get_default_config_path()
            change_current_user(config_path, username)

            return redirect(reverse('voice_app:index'))
    else:
        form = ReloginForm()

    return render(request, 'voice_app/relogin.html', {'form': form})


@pass_current_user_id_factory(create_ctx)
def user_info(user_id, fake_id, request):
    ctx = create_ctx()

    return render(request, 'voice_app/current_user.html', {
        'username': ctx.voice.user_service.select([user_id])[0],
        'fake': ctx.voice.fake_service.select([fake_id])[0]
    })


@pass_current_user_id_factory(create_ctx)
def add_blog(user_id, fake_id, request):
    ctx = create_ctx()

    if request.method == 'POST':
        form = AddBlogForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']

            voice = ctx.voice

            blog = Blog(title=title, creator_id=fake_id)

            voice.blog_service.add(blog)

            return redirect(reverse('voice_app:index'))
    else:
        form = AddBlogForm()

    return render(request, 'voice_app/add_blog.html', {'form': form})


@pass_current_user_id_factory(create_ctx)
def show_blog(user_id, fake_id, request):
    ctx = create_ctx()

    blog_id = int(request.GET['blog_id'])

    voice = ctx.voice
    print("blog_id:", blog_id)

    blogs = voice.blog_service.select([blog_id])
    print("blogs_len:", len(blogs))
    if len(blogs) == 0:
        print("Object with this id is not exists")
        return 0

    blog = blogs[0]

    blogs = voice.blog_service.select([blog_id])

    posts = voice.post_service.select_by_blog(blog_id)

    return render(request, 'voice_app/show_blog.html', {'blog': blog, 'posts': posts, 'user_id': user_id})


@pass_current_user_id_factory(create_ctx)
def blog_list(user_id, fake_id, request):
    ctx = create_ctx()

    voice = ctx.voice

    blogs = voice.blog_service.get_all()

    return render(request, 'voice_app/blog_list.html', {'blogs': blogs, 'user_id': user_id})


@pass_current_user_id_factory(create_ctx)
def edit_blog(user_id, fake_id, request):
    ctx = create_ctx()

    blog_id = int(request.GET['blog_id'])

    if request.method == 'POST':
        form = EditBlogForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']

            voice = ctx.voice

            blogs = voice.blog_service.select([blog_id])

            blog = blogs[0]
            blog.title = title
            voice.blog_service.update(blog)

            return redirect(reverse('voice_app:show_blog') + '?blog_id={}'.format(blog_id))
    else:
        form = EditBlogForm()

    return render(request, 'voice_app/edit_blog.html', {'form': form})


def remove_blog(request):
    ctx = create_ctx()

    blog_id = int(request.GET['blog_id'])

    voice = ctx.voice

    blogs = voice.blog_service.select([blog_id])

    blog = blogs[0]
    voice.blog_service.remove([blog.id])

    return redirect(reverse('voice_app:index'))


def add_cat(request):
    ctx = create_ctx()

    if request.method == 'POST':
        form = AddCatForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']

            voice = ctx.voice

            category = Category(name=name, )

            voice.category_service.add(category)

            return redirect(reverse('voice_app:index'))
    else:
        form = AddCatForm()

    return render(request, 'voice_app/add_cat.html', {'form': form})


def all_cats(request):
    ctx = create_ctx()

    voice = ctx.voice

    categorys = voice.category_service.select_all()

    return render(request, 'voice_app/all_cats.html', {'cats': categorys})


def edit_cat(request):
    ctx = create_ctx()

    category_id = int(request.GET['cat_id'])

    if request.method == 'POST':
        form = EditCatForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']

            voice = ctx.voice

            categorys = voice.category_service.select([category_id])

            category = categorys[0]
            category.name = name
            voice.category_service.update(category)

            return redirect(reverse('voice_app:index'))
    else:
        form = EditCatForm()

    return render(request, 'voice_app/edit_cat.html', {'form': form})


def remove_cat(request):
    ctx = create_ctx()

    category_id = int(request.GET['cat_id'])

    voice = ctx.voice

    categorys = voice.category_service.select([category_id])

    category = categorys[0]
    voice.category_service.remove([category.id])

    return redirect(reverse('voice_app:index'))


@pass_current_user_id_factory(create_ctx)
def add_comment(user_id, fake_id, request):
    ctx = create_ctx()

    post_id = int(request.GET['post_id'])

    if request.method == 'POST':
        form = AddCommentForm(request.POST)

        if form.is_valid():
            content = form.cleaned_data['content']

            voice = ctx.voice

            comment = Comment(
                content=content,
                creator_id=fake_id,
                post_id=post_id,
            )

            voice.comment_service.add(comment)

            return redirect(reverse('voice_app:show_post') + '?post_id={}'.format(post_id))
    else:
        form = AddCommentForm()

    return render(request, 'voice_app/add_comment.html', {'form': form})


@pass_current_user_id_factory(create_ctx)
def edit_comment(user_id, fake_id, request):
    ctx = create_ctx()

    comment_id = int(request.GET['comment_id'])

    if request.method == 'POST':
        form = EditCommentForm(request.POST)

        if form.is_valid():
            content = form.cleaned_data['content']

            voice = ctx.voice

            comments = voice.comment_service.select([comment_id])

            comment = comments[0]
            comment.content = content
            voice.comment_service.update(comment)

            return redirect(reverse('voice_app:all_comments') + '?post_id={}'.format(comment.post_id))
    else:
        form = EditCommentForm()

    return render(request, 'voice_app/edit_comment.html', {'form': form})


@pass_current_user_id_factory(create_ctx)
def remove_comment(user_id, fake_id, request):
    ctx = create_ctx()

    comment_id = int(request.GET['comment_id'])

    voice = ctx.voice

    comments = voice.comment_service.select([comment_id])

    comment = comments[0]
    voice.comment_service.remove([comment.id])

    return redirect(reverse('voice_app:show_post') + '?post_id={}'.format(comment.post_id))


@pass_current_user_id_factory(create_ctx)
def all_comments(user_id, fake_id, request):
    ctx = create_ctx()

    post_id = int(request.GET['post_id'])

    voice = ctx.voice

    comments = voice.comment_service.select_by_post(post_id)
    fakes = voice.fake_service.select([comment.creator_id for comment in comments])

    for comment in comments:
        comment.nickname = next(fake.nickname for fake in fakes if fake.id == comment.creator_id)

    return render(request, 'voice_app/comments.html', {
        'comments': comments,
        'user_id': fake_id,
    })


@pass_current_user_id_factory(create_ctx)
def add_post(user_id, fake_id, request):
    ctx = create_ctx()

    blog_id = int(request.GET['blog_id'])

    if request.method == 'POST':
        form = AddPostForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            category_id = int(form.cleaned_data['category_id'])
            """Create post from current fake of user."""
            voice = ctx.voice

            post = Post(
                title=title,
                content=content,
                blog_id=blog_id,
                category_id=category_id,
            )

            voice.post_service.add(post)

            return redirect(reverse('voice_app:show_blog') + '?blog_id={}'.format(blog_id))
    else:
        form = AddPostForm()

    return render(request, 'voice_app/add_post.html', {'form': form})


@pass_current_user_id_factory(create_ctx)
def edit_post(user_id, fake_id, request):
    ctx = create_ctx()

    post_id = int(request.GET['post_id'])

    if request.method == 'POST':
        form = EditPostForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            category_id = int(form.cleaned_data['category_id'])

            voice = ctx.voice

            posts = voice.post_service.select([post_id])

            post = posts[0]
            post.title = title
            post.content = content
            post.category_id = category_id

            voice.post_service.update(post)

            return redirect(reverse('voice_app:show_post') + '?post_id_id={}'.format(post_id))
    else:
        form = EditPostForm()

    return render(request, 'voice_app/edit_post.html', {'form': form})

voice_web/voice_app/templates/voice_app/_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fake blogs</title>
    <link rel="stylesheet"
        href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet"
        href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"
        />
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="header">
        <div class="inner">
            <div style="float: left;">
                <a class="mr-5" href="/">Home</a>
                <a href="{% url 'voice_app:add_blog' %}">Create blog</a>
                <a href="{% url 'voice_app:add_cat' %}">Add category</a>
            </div>
            <div style="float: right">
                <a href="{% url 'voice_app:userinfo' %}">Info</a>
                <a href="{% url 'voice_app:change_nickname' %}">Switch nickname</a>
                <a href="{% url 'voice_app:relogin' %}">Change profile</a>
            </div>
            <div style="clear: both;"></div>
        </div>
    </div>
    <div class="content">
    
        {% block content %}
        {% endblock content %}

    </div>
</body>
</html>

voice_web/voice_app/templates/voice_app/add_blog.html
{% extends  "voice_app/_base.html" %}

{% block content %}

<form action="{% url 'voice_app:add_blog' %}" method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input class="ui button primary" type="submit" value="Go">
    <a class="ui button" href="{% url 'voice_app:index' %}">Back</a>

</form>

{% endblock content %}

voice_web/voice_app/templates/voice_app/add_cat.html
{% extends  "voice_app/_base.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input class="ui button primary" type="submit" value="Go">
    <a class="ui button" href="{% url 'voice_app:index' %}">Back</a>

</form>

{% endblock content %}

voice_web/voice_app/templates/voice_app/add_comment.html
{% extends  "voice_app/_base.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input class="ui button primary" type="submit" value="Go">

</form>

{% endblock content %}

voice_web/voice_app/templates/voice_app/all_cats.html
{% extends  "voice_app/_base.html" %}

{% block content %}

<h2>Categories:</h2>

{% for cat in cats %}

{% include "voice_app/partials/_cat.html" with cat=cat %}
<a href="{% url 'voice_app:edit_cat' %}?cat_id={{ cat.id }}">Edit</a>
<a class="red" href="{% url 'voice_app:remove_cat' %}?cat_id={{ cat.id }}">Delete</a>

{% endfor %}

{% endblock content %}

voice_web/voice_app/templates/voice_app/change_nickname.html
{% extends  "voice_app/_base.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input class="ui button primary" type="submit" value="Go">
    <a class="ui button" href="{% url 'voice_app:index' %}">Back</a>

</form>

{% endblock content %}

voice_web/voice_app/templates/voice_app/comments.html
{% extends  "voice_app/_base.html" %}

{% block content %}

<h2>Comments:</h2>

{% for comment in comments %}

<p>
    {{ comment.nickname }}:
    <div style="position: relative; left: 10px; bottom: 10px;">
    {{ comment.content }}
    </div>

    {% if user_id == comment.creator_id %}

    <a href="{% url 'voice_app:edit_comment' %}?comment_id={{ comment.id }}">Edit</a>
    <a href="{% url 'voice_app:remove_comment' %}?comment_id={{ comment.id }}">Delete</a>

    {% endif %}
</p>

{% endfor %}

{% endblock content %}

voice_web/voice_app/templates/voice_app/current_user.html
{% extends 'voice_app/_base.html' %}

{% block content %}

<p>Current user: {{ username.login }}</p>
<p>Fake: {{ fake.nickname }}</p>

{% endblock content %}

voice_web/voice_app/templates/voice_app/edit_blog.html
{% extends  "voice_app/_base.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input class="ui button primary" type="submit" value="Go">
    <a class="ui button" href="{% url 'voice_app:index' %}">Back</a>

</form>

{% endblock content %}

voice_web/voice_app/templates/voice_app/edit_cat.html
{% extends  "voice_app/_base.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input class="ui button primary" type="submit" value="Go">
    <a class="ui button" href="{% url 'voice_app:index' %}">Back</a>

</form>

{% endblock content %}

voice_web/voice_app/templates/voice_app/edit_comment.html
{% extends  "voice_app/_base.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input class="ui button primary" type="submit" value="Go">

</form>

{% endblock content %}

voice_web/voice_app/templates/voice_app/edit_post.html
{% extends  "voice_app/_base.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input class="ui button primary" type="submit" value="Go">

</form>

{% endblock content %}

voice_web/voice_app/templates/voice_app/index.html
{% extends "voice_app/_base.html" %} 

{% block content %}

<p>Quick links:</p>
<ul>
    <li><a href="{% url 'voice_app:relogin' %}">Relogin</a></li>
    <li><a href="{% url 'voice_app:userinfo' %}">User info</a></li>
    <li><a href="{% url 'voice_app:add_blog' %}">Add blog</a></li>
    <li><a href="{% url 'voice_app:blog_list' %}">View blogs</a></li>
    <li><a href="{% url 'voice_app:add_cat' %}">Add category</a></li>
    <li><a href="{% url 'voice_app:all_cats' %}">View categories</a></li>

    <li><a href="{% url 'voice_app:relogin' %}">Relogin</a></li>
    <li><a href="{% url 'voice_app:relogin' %}">Relogin</a></li>
</ul>

{% endblock content %}

voice_web/voice_app/templates/voice_app/relogin.html
{% extends  "voice_app/_base.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input class="ui button primary" type="submit" value="Go">
    <a class="ui button" href="{% url 'voice_app:index' %}">Back</a>

</form>

{% endblock content %}